sudo: required
services:
    - docker

before_install:
    - docker build -t cfaguilera20/docker-react-aws -f Dockerfile.dev .

script:
    - docker run cfaguilera20/docker-react-aws npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'docker-react-aws'
    env: 'DockerReactAws-env'
    bucket_name: 'elasticbeanstalk-us-east-1-330478549731'
    bucket_path: 'docker-react-aws'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: '$AWS_SECRET_KEY'
